### ISSUE TITLE
Release `42170` is broken - Fails to start

### ISSUE THREAD

**Issue by ThaDaVos** [gh0st-work/clear-linux-wsl#3]
I already created an issue generically - but this one is specifically stating that the mentioned release does not work - it's missing files internally
https://github.com/gh0st-work/clear-linux-wsl/issues/2

**Comment by ThaDaVos** [comment]
I guess @gh0st-work it's something wrong with the pipeline since version `42150` as then the image size decreased

**Comment by gh0st-work** [comment]
Thanks for reporting. Probably, `sudo tar ...` command somehow ignores some files, I'll try to fix it in a few days. [Release `41760`](https://github.com/gh0st-work/clear-linux-wsl/releases/tag/41760) is recommended for now.

**Comment by gh0st-work** [comment]
Latest release [42210](https://github.com/gh0st-work/clear-linux-wsl/releases/tag/42210) works on my machine following the instructions. I'll just delete releases 42150 and 42170.
